before_script:
  - "ruby --version"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rake"
notifications:
  email:
    - ryan@spreecommerce.com
  irc: "irc.freenode.org#spree"
branches:
  only:
    - master
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
